Update package.json
Bump ssh2 to Fix TypeError: isDate is not a function caused by ssh2, they fixed it here:

https://github.com/mscdex/ssh2/commit/4f771c92daab356afbe56f0a40ea2a540b0b6beb